/*CLEAR SCREEN

COMMIT;

EXECUTE probar_mi_t2;

DROP SEQUENCE SEC_T2;
*/
CREATE SEQUENCE SEC_T2 MINVALUE 0 MAXVALUE 1 START WITH 0 INCREMENT BY 1 CYCLE NOCACHE;


CREATE OR REPLACE PROCEDURE TRABAJANDO_T2(X IN NUMBER) AS

    ESTADO_ACTUAL NUMBER;
    ESTADO_ANTERIOR NUMBER;
    ID_Tran varchar(50);
    
BEGIN
    
    LOOP
    
        SELECT  SEC_T2.NEXTVAL into ESTADO_ACTUAL FROM dual ; 
        
        IF  ESTADO_ACTUAL = ESTADO_ANTERIOR THEN EXIT;
        ELSE
   
            ESTADO_ANTERIOR := ESTADO_ACTUAL;
            DORMIR(X);
   
        END IF;
   
    END LOOP;
 
    SELECT dbms_transaction.local_transaction_id into ID_Tran FROM dual;
    DBMS_OUTPUT.PUT_LINE('TRANSACCION DORMIDA: ' || ID_Tran);
    DBMS_OUTPUT.PUT_LINE('TRABAJANDO_T2: HE TERMINADO DE TRABAJAR.');

END;


CREATE OR REPLACE PROCEDURE PROBAR_MI_T2 AS
BEGIN
    
    --SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; --APARTADO D 

     DBMS_OUTPUT.PUT_LINE('ANTES DE LA PRIMERA INSERCION.');

    INSERT INTO Compras VALUES ('00000003', '30000020',4, 101,'tienda1',4839);
    INSERT INTO Compras VALUES ('00000004', '40000200',5, 202,'tienda2',897);
    INSERT INTO Compras VALUES ('00000005', '50000400',6, 303,'tienda3',9736);
    
     DBMS_OUTPUT.PUT_LINE('PRIMERA INSERCION COMPLETADA.');
    
    TRABAJANDO_T2(5);
    
     DBMS_OUTPUT.PUT_LINE('ANTES DE LA SEGUNDA INSERCION.');
    
    INSERT INTO Compras VALUES ('00000003', '30000020',7, 404,'tienda4',238);
    INSERT INTO Compras VALUES ('00000004', '40000200',8, 505,'tienda5',4892);
    INSERT INTO Compras VALUES ('00000005', '50000400',9, 606,'tienda6',972);
    
     DBMS_OUTPUT.PUT_LINE('SEGUNDA INSERCION COMPLETADA.');
    
    TRABAJANDO_T2(5);
    
END;